version: 0.1
env:
  - name: CLOWDER_CONFIG
    value: $(volumeMounts:config-secret)/cdappconfig.json
  - name: RH_CDN_CERT_PAIR
    value: |
      -----BEGIN CERTIFICATE-----
      <certificate jargon>
      -----END CERTIFICATE-----
      -----BEGIN RSA PRIVATE KEY-----
      <more certificate jargon>
      -----END RSA PRIVATE KEY-----

volumeMounts:
  - name: config-secret
    localPath: /cdapp
